### ISSUE TITLE
Is this correct PLbetweenIndoor Nodes ?

### ISSUE THREAD

**Issue by wiless** [wiless/cellular#6]
https://github.com/wiless/cellular/blob/16d0b41b8074a8fd62a2954c9b755fb9308561bb/func.go#L108

Did this come because of InH testing ? Hope this is correctly called ? @vishakhadhanwani

**Comment by vishakhadhanwani** [comment]
This function has nothing to do specifically with InH .This is used to
calculate pathloss value for all environments be it RMa, UMa or InH.

**Comment by wiless** [comment]
got it.. dIn subtracts that distance during the PL calculation..

**Comment by vishakhadhanwani** [comment]
This dIn is used in case of RMa and UMa Environment in equation d2d-dIn to
allocate users flag of LOS or NLOS .In calculating pathloss values d2d is
used only for thresholding and then using d2d,dIn,HBS and HUT ,d3In is
calculated which is further subtracted from d3d i.e d3dout=d3d-d3In.To
calculate pathloss finally d3dout is used.
